
email: admin@university.edu # Email for NCBI registration (required for API usage).
# artifacts paths
data_path: ~/data/cafa6_data # path to input data
embed_path: ~/data/cafa6_embeds
models_path: ~/data/cafa6_models

devices:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
