
email: admin@university.edu # Email for NCBI registration (required for API usage).
# artifacts paths. Pls put absolute path here
data_path: /workspace/data/cafa6_data # path to input data
embed_path: /workspace/data/cafa6_embeds
models_path: /workspace/data/cafa6_models

devices:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
