
train_data: cafa6 # options cafa6/cafa5

train_params:
  n_ep: 1
  store_swa: 10
  use_swa: 3
  p_goa: 0.5
  num_workers: 8
  batch_size: 32
  test_batch_size: 512

  lr: 0.001
  clip_grad: 0.1
  weight_decay: 0.00001

  hidden_size: 16
  n_layers: 8
  embed_size: 8

models:
  - ./models/lin_cafa5_t5_uniprot-sparse-labels13500_cond/
  - ./models/pb_cafa5_t5esm2S1280_uniprot-sparse-labels4500_cond/


tta:
  cfg0:
    - ./models/lin_cafa5_t5_uniprot-sparse-labels13500_cond/
    - ./models/pb_cafa5_t5esm2S1280_uniprot-sparse-labels4500_cond/

