name: pb_t5esm4500_raw
embeds:
    - t5
    - esm2S1280
conditional: false
bp: 300
mf: 100
cc: 50

train_labels: cafa6-sparse-labels
old_train_labels: uniprot-old-sparse-labels

train_data: cafa5 # options cafa6/cafa5
valid_data: cafa6 # options cafa6/cafa5

train_params:
  ntrees: 100
  lr: 0.03
  verbose: 100
  es: 300
  lambda_l2: 10
  gd_steps: 1
  subsample: 0.8
  colsample: 0.8
  min_data_in_leaf: 10
  use_hess: False
  max_bin: 256
  max_depth: 6

  sketch_size: 3

tax_list:
    - 9606
    - 3702
    - 10090
    - 7955
    - 7227
    - 10116
    - 559292
    - 6239
    - 284812
    - 83333
    - 83332
    - 44689
    - 237561
    - 39947
    - 9031
    - 36329
    - 9913
    - 227321
    - 8355
    - 9823
    - 224308
    - 330879
    - 4577
    - 170187
    - 9615
    - 99287
    - 85962
    - 243232
    - 287
    - 235443
    - 8364
